[package]
name = "sni_prob"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
colored = "3.0.0"
indicatif = "0.18.3"
rustls = { version = "0.23.35", default-features = false, features = ["ring", "logging", "std", "tls12"] }
webpki-roots = "1.0.5"
