[target.loongarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-gnu:edge"

[target.loongarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-musl:edge"

[target.x86_64-unknown-netbsd]
dockerfile = "./docker/Dockerfile.x86_64-unknown-netbsd"

[target.x86_64-pc-solaris]
dockerfile = "./docker/Dockerfile.x86_64-pc-solaris"

[target.x86_64-pc-solaris.env]
RUSTFLAGS = "-C link-arg=-L/usr/local/solaris-shims -C link-arg=-Wl,--allow-shlib-undefined -C link-arg=-Wl,--warn-unresolved-symbols"
